### ISSUE TITLE
how to ensure if the user is logged in with twitter only

### ISSUE THREAD

**Issue by Sarfarazsajjad** [jaredhanson/connect-ensure-login#13]
what if there are multiple options like facebook, twitter, google and local; for the user to login to our app and on a specific route we want to check if the user is logged in with twitter. how can i ensure if the user is authenticated and logged in with twitter. if the user is not logged in with twitter then i want the user to first login with twitter and then redirect to the same page again

**Comment by aoberoi** [comment]
it sounds like you should just use `passport.authenticate('twitter')` as a middleware on the route.

**Comment by jaredhanson** [comment]
Not an issue with this project, closing.  Please ask questions on a suitable discussion forum.
